### ISSUE TITLE
Image Sizing

### ISSUE THREAD

**Issue by machewgc** [machewgc/roles#1]
The size of the generic good image is such that it doesn't take up the same height as the other good images. This creates a scenario where the 4th column (the assassin) gets aligned under the generic good column instead of on the left side. I did a quick fix by adding line breaks in front of the generic good image. See if you can make the columns align correctly without using line breaks.

**Comment by mattsuid** [comment]
I explicitly defined dimensions for the image class and then removed line breaks. I wan't able to reproduce the issue though.

ps: also added readme
